"""
Vocalis API
-----------
Text-to-speech backend, with a free daily credit system per device
(no login required — a random device id is generated by the frontend
and stored in its browser localStorage).

Endpoints:
  GET  /               -> health check
  GET  /voices?lang=..  -> list available voices (optionally filtered by locale)
  GET  /languages       -> list available locales
  GET  /credits          -> check a device's remaining credits (does not deduct)
  POST /speak            -> { text, voice, rate, pitch } -> returns MP3 audio
                             requires header X-Device-Id
                             optional header X-Usage-Type: "audio" (default) or "video"

Setup:
  Add these environment variables in Vercel (Project Settings -> Environment Variables):
    SUPABASE_URL          -> from Supabase Project Settings -> API
    SUPABASE_SERVICE_KEY   -> the "service_role" secret key (NOT the anon key)
  Then run credits_schema.sql once in Supabase's SQL editor.
"""

from fastapi import FastAPI, HTTPException, Response, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import edge_tts
import asyncio
import time
import os
import datetime

app = FastAPI(title="Vocalis API", version="1.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["X-Credits-Remaining"],
)

_voice_cache: list[dict] | None = None

# ---------------------------------------------------------------------------
# Credits
# ---------------------------------------------------------------------------

DAILY_FREE_CREDITS = 30
COST_AUDIO = 1
COST_VIDEO = 5

_supabase = None


def _get_supabase():
    """Lazily create the Supabase client using the service role key.
    Returns None if env vars are not configured yet, so the API still
    runs (with credits effectively unlimited) before setup is finished."""
    global _supabase
    if _supabase is not None:
        return _supabase
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_KEY")
    if not url or not key:
        return None
    try:
        from supabase import create_client
        _supabase = create_client(url, key)
        return _supabase
    except Exception as e:
        print(f"[credits] Supabase client failed to init: {e}", flush=True)
        return None


def _check_and_deduct_credits(device_id: str, cost: int) -> int:
    """Returns remaining credits after deducting `cost`.
    Raises HTTPException(429) if the device has run out.
    If Supabase isn't configured yet, credits are not enforced (returns -1)."""
    sb = _get_supabase()
    if sb is None:
        return -1  # credits not enforced yet

    today = datetime.date.today().isoformat()
    row = sb.table("device_credits").select("*").eq("device_id", device_id).execute()

    if row.data:
        record = row.data[0]
        credits = record["credits"]
        last_reset = record["last_reset"]
        if last_reset != today:
            credits = DAILY_FREE_CREDITS
    else:
        credits = DAILY_FREE_CREDITS

    if credits < cost:
        raise HTTPException(
            status_code=429,
            detail=f"Out of free credits for today (need {cost}, have {credits}). "
                   f"Credits reset at midnight.",
        )

    remaining = credits - cost
    sb.table("device_credits").upsert({
        "device_id": device_id,
        "credits": remaining,
        "last_reset": today,
    }).execute()
    return remaining


@app.get("/credits")
async def get_credits(x_device_id: str | None = Header(default=None)):
    if not x_device_id:
        raise HTTPException(status_code=400, detail="X-Device-Id header is required")
    sb = _get_supabase()
    if sb is None:
        return {"credits": None, "enforced": False, "daily_limit": DAILY_FREE_CREDITS}

    today = datetime.date.today().isoformat()
    row = sb.table("device_credits").select("*").eq("device_id", x_device_id).execute()
    if row.data:
        record = row.data[0]
        credits = record["credits"] if record["last_reset"] == today else DAILY_FREE_CREDITS
    else:
        credits = DAILY_FREE_CREDITS
    return {"credits": credits, "enforced": True, "daily_limit": DAILY_FREE_CREDITS}


# ---------------------------------------------------------------------------
# Voices
# ---------------------------------------------------------------------------

def _friendly_name(short_name: str) -> str:
    name = short_name.split("-")[-1]
    name = name.replace("Neural", "")
    if "Multilingual" in name:
        name = name.replace("Multilingual", "") + " (Multilingual)"
    return name.strip()


@app.get("/")
async def root():
    return {"status": "ok", "message": "Vocalis API is running"}


@app.get("/voices")
async def get_voices(lang: str | None = None):
    global _voice_cache
    if _voice_cache is None:
        _voice_cache = await edge_tts.list_voices()

    voices = _voice_cache
    if lang:
        voices = [v for v in voices if v["Locale"].lower().startswith(lang.lower())]

    return [
        {
            "id": v["ShortName"],
            "name": _friendly_name(v["ShortName"]),
            "gender": v["Gender"],
            "locale": v["Locale"],
        }
        for v in voices
    ]


@app.get("/languages")
async def get_languages():
    global _voice_cache
    if _voice_cache is None:
        _voice_cache = await edge_tts.list_voices()
    return sorted({v["Locale"] for v in _voice_cache})


# ---------------------------------------------------------------------------
# Speak
# ---------------------------------------------------------------------------

class SpeakRequest(BaseModel):
    text: str
    voice: str = "en-US-AnaNeural"
    rate: str = "+0%"
    pitch: str = "+0Hz"


@app.post("/speak")
async def speak(
    req: SpeakRequest,
    x_device_id: str | None = Header(default=None),
    x_usage_type: str | None = Header(default="audio"),
):
    text = req.text.strip()
    if not text:
        raise HTTPException(status_code=400, detail="Text is required")
    if len(text) > 100000:
        raise HTTPException(status_code=400, detail="Text too long (max 100,000 characters)")

    # Credits are only enforced when a caller sends X-Device-Id (the new
    # Script to Video tab does this). Calls without it — like the original
    # unlimited text-to-speech box — are never rate-limited, so nothing
    # about the existing site changes.
    remaining = -1
    if x_device_id:
        cost = COST_VIDEO if x_usage_type == "video" else COST_AUDIO
        remaining = _check_and_deduct_credits(x_device_id, cost)

    async def _synthesize() -> bytes:
        t0 = time.perf_counter()
        communicate = edge_tts.Communicate(text, req.voice, rate=req.rate, pitch=req.pitch)
        audio = bytearray()
        chunk_count = 0
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                audio.extend(chunk["data"])
                chunk_count += 1
        elapsed = time.perf_counter() - t0
        print(f"[speak] voice={req.voice} chars={len(text)} chunks={chunk_count} "
              f"bytes={len(audio)} elapsed={elapsed:.2f}s cost={cost}", flush=True)
        return bytes(audio)

    try:
        req_t0 = time.perf_counter()
        audio_bytes = await asyncio.wait_for(_synthesize(), timeout=55)
        print(f"[speak] total request time={time.perf_counter()-req_t0:.2f}s", flush=True)
    except asyncio.TimeoutError:
        print(f"[speak] TIMED OUT after 55s for voice={req.voice} chars={len(text)}", flush=True)
        raise HTTPException(
            status_code=504,
            detail="Voice generation timed out. Try shorter text, or try again in a moment.",
        )

    if not audio_bytes:
        raise HTTPException(status_code=502, detail="No audio was generated. Try again.")

    headers = {"Content-Disposition": "inline; filename=speech.mp3"}
    if remaining >= 0:
        headers["X-Credits-Remaining"] = str(remaining)

    return Response(
        content=audio_bytes,
        media_type="audio/mpeg",
        headers=headers,
    )
